from groq import Groq
from config import GROQ_API_KEY, LLM_MODEL
import json
import re

_client = Groq(api_key=GROQ_API_KEY)



def get_llm_score(text: str) -> float:
    try:
        system_prompt = """You are an expert AI content detector. Analyze the given text and determine 
    whether it was written by a human or generated by AI.

    Look for these patterns:
    - AI text: uniform sentence length, perfect grammar, formal vocabulary, 
    no personal voice, overly balanced structure
    - Human text: varied sentence length, informal markers, personal opinions, 
    typos, contractions, emotional language

    Respond in JSON only, no other text:
    {"ai_probability": float value, "reasoning": "one sentence explanation of your reasoning, including any patterns you observed in the text."}

    Where ai_probability is between 0.0 (definitely human) and 1.0 (definitely AI)."""
    
        response = _client.chat.completions.create(
            model=LLM_MODEL,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": text}
            ],
            temperature=0.0
        )
        raw_text = response.choices[0].message.content.strip()
        data = json.loads(raw_text)
        return float(data["ai_probability"])
    except Exception as e:
        print(f"Error in get_llm_score: {e}")
        return 0.5  # Return a neutral score if there's an error
    

def get_stylometric_score(text: str) -> float:
    sentences = re.split(r'[.!?]+', text)
    sentences = [s.strip() for s in sentences if s.strip()]
    
    if len(sentences) < 2:
        return 0.5  # not enough text, return uncertain
    
    lengths = [len(s.split()) for s in sentences]
    mean_len = sum(lengths) / len(lengths)
    variance = sum((l - mean_len) ** 2 for l in lengths) / len(lengths)
    
    # High variance = human, low variance = AI
    variance_score = 1 - min(variance / 50, 1.0)
    
    words = text.lower().split()
    ttr = len(set(words)) / len(words) if words else 0.5
    ttr_score = 1 - ttr
    
    return round((variance_score + ttr_score) / 2, 3)   


def get_informality_score(text: str) -> float:
    text_lower = text.lower()
    
    informal_words = [
        "ok", "okay", "gonna", "wanna", "kinda", "sorta",
        "lol", "omg", "brb", "btw", "tbh", "ngl", "imo",
        "gn8", "tc", "hi", "hey", "yeah", "yep", "nope",
        "cause", "coz", "dunno", "gimme", "lemme"
    ]
    
    informal_count = sum(1 for word in informal_words 
                        if re.search(r'\b' + word + r'\b', text_lower))
    
    casual_punctuation = len(re.findall(r'\.{2,}|!{2,}|\?{2,}', text))
    
    words = text.split()
    if not words:
        return 0.5
    
    informality_ratio = (informal_count + casual_punctuation) / len(words)
    
    # High informality = human (score close to 0.0)
    # Low informality = AI-like (score close to 1.0)
    return round(1 - min(informality_ratio * 10, 1.0), 3)